 version=0.1

 [default.deploy.parameters]
 stack_name = "sam-mongo-sandbox"
 s3_bucket = "uk.co.morganshaw.sandbox.sam"
 s3_prefix = "samdeploy"
 region = "eu-west-1"
 confirm_changeset = true
 capabilities = "CAPABILITY_IAM"
 profile = "sandbox"

 [default.build.parameters]
 beta_features = true