AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM project for API

Parameters:
  DatabaseConnectionString:
    Type: String
    Default: "mongodb://host.docker.internal:27017/renewable-energy-homes"

Globals:
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowHeaders: "'*'"
      AllowMethods: "'*'"
  Function:
    Runtime: nodejs14.x
    Timeout: 30
    Environment:
      Variables:
        DatabaseConnectionString: !Ref DatabaseConnectionString    

Resources:
  Health:
    Type: AWS::Serverless::Function
    Properties:
      Handler: health.handler
      CodeUri: src/resources/health/
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /health
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - health.ts

  BookingsList:
    Type: AWS::Serverless::Function
    Properties:
      Handler: list.handler
      CodeUri: src/resources/booking/
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /booking
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - list.ts

  BookingsGetById:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getById.handler
      CodeUri: src/resources/booking/
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /booking/{bookingId}
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - getById.ts

  BookingsCreate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create.handler
      CodeUri: src/resources/booking/
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /booking
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - create.ts

  PropertySearch:
    Type: AWS::Serverless::Function
    Properties:
      Handler: search.handler
      CodeUri: src/resources/property/
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /property/search/{postcode}
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - search.ts        